version: '3'
services:
  # Setup PostgreSQL
  be_node_hapi_pg_db:
    image: 'postgres:15' 
    ports:
      - 5432:5432 
    restart: always # This will make sure that the container comes up post unexpected shutdowns
    env_file:
      - ./be-node-hapi-pg/.env.docker
    volumes:
      - be-node-hapi-pg-db-volume:/var/lib/postgresql/data

  # Setup be-node-hapi-pg api
  be-node-hapi-pg:
    build:
      context: './be-node-hapi-pg'
      args:
        ENVIRONMENT_NAME: docker
    ports:
      - 9000:9000
    env_file:
      - ./be-node-hapi-pg/.env.docker
    environment:
      ENVIRONMENT_NAME: docker


  # Setup Redis
  redis:
    image: 'redis:6-alpine'
    ports:
      - 6379:6379
    # Default command that redis will execute at start
    command: ['redis-server']

# No web stacks present


# Setup Volumes
volumes:
  be-node-hapi-pg-db-volume:

